[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/save-score"
  to = "/.netlify/functions/save-score"
  status = 200
  force = true

[[redirects]]
  from = "/applicants"
  to = "/.netlify/functions/applicants"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
