"""
Builds views/partials/coverage-map.ejs — the homepage's animated coverage map.

Run once whenever the covered districts change:
  pip install shapely
  curl -L -o /tmp/lad.json https://raw.githubusercontent.com/martinjc/UK-GeoJSON/master/json/administrative/eng/lad.json
  python3 scripts/build-coverage-map.py /tmp/lad.json

Boundaries: ONS Local Authority Districts (Open Government Licence), via martinjc/UK-GeoJSON.
Each covered district becomes a link; its href is resolved at render time by
mapLink(regionName) in server.js, so new area pages in Supabase become
clickable automatically.
"""
import json, math, sys, os
from shapely.geometry import shape, box, mapping
from shapely.ops import unary_union

SRC = sys.argv[1] if len(sys.argv) > 1 else '/tmp/lad.json'
OUT = os.path.join(os.path.dirname(__file__), '..', 'views', 'partials', 'coverage-map.ejs')

LONDON = ['Barking and Dagenham','Barnet','Bexley','Brent','Bromley','Camden','Croydon','Ealing','Enfield',
  'Greenwich','Hackney','Hammersmith and Fulham','Haringey','Harrow','Havering','Hillingdon','Hounslow',
  'Islington','Kensington and Chelsea','Kingston upon Thames','Lambeth','Lewisham','Merton','Newham',
  'Redbridge','Richmond upon Thames','Southwark','Sutton','Tower Hamlets','Waltham Forest','Wandsworth','Westminster']
# district -> (label shown to visitors, coverage region name in Supabase)
ESSEX = {
  'Thurrock': ('Thurrock', 'Essex - Romford / Thurrock Edge'),
  'Brentwood': ('Brentwood', 'Essex - Brentwood'),
  'Basildon': ('Basildon', 'Essex - Basildon'),
  'Chelmsford': ('Chelmsford', 'Essex - Chelmsford'),
  'Castle Point': ('Benfleet & Canvey Island', 'Essex - Benfleet'),
  'Rochford': ('Rayleigh', 'Essex - Rayleigh'),
  'Southend-on-Sea': ('Southend & Leigh-on-Sea', 'Essex - Southend-on-Sea'),
}
COVERED = {n: (n, n, 'london') for n in LONDON}
COVERED.update({k: (v[0], v[1], 'essex') for k, v in ESSEX.items()})

feats = json.load(open(SRC))['features']
geoms = {f['properties']['LAD13NM']: shape(f['geometry']).buffer(0) for f in feats}

covered_union = unary_union([geoms[n] for n in COVERED])
minx, miny, maxx, maxy = covered_union.bounds
px, py = (maxx - minx) * 0.05, (maxy - miny) * 0.08
frame = box(minx - px, miny - py, maxx + px, maxy + py)
fx0, fy0, fx1, fy1 = frame.bounds

lat0 = math.radians((fy0 + fy1) / 2)
W = 1000.0
kx = W / ((fx1 - fx0) * math.cos(lat0))
H = (fy1 - fy0) * kx
def proj(lon, lat):
    return ((lon - fx0) * math.cos(lat0) * kx, (fy1 - lat) * kx)

TOL = (fx1 - fx0) / 900  # simplification tolerance in degrees (~1px)

def path_d(g):
    g = g.simplify(TOL, preserve_topology=True)
    polys = [g] if g.geom_type == 'Polygon' else list(getattr(g, 'geoms', []))
    out = []
    for p in polys:
        if p.geom_type != 'Polygon' or p.area < (TOL * TOL * 4):
            continue
        for ring in [p.exterior, *p.interiors]:
            pts = [proj(x, y) for x, y in ring.coords]
            out.append('M' + 'L'.join(f'{x:.1f} {y:.1f}' for x, y in pts) + 'Z')
    return ''.join(out)

# Context: every other district touching the frame, muted and not clickable.
context = []
for name, g in geoms.items():
    if name in COVERED or not g.intersects(frame):
        continue
    d = path_d(g.intersection(frame))
    if d:
        context.append(f'<path d="{d}"/>')

areas = []
order = sorted(COVERED, key=lambda n: geoms[n].centroid.x)  # animate west -> east
for i, name in enumerate(order):
    label, region, group = COVERED[name]
    d = path_d(geoms[name])
    c = geoms[name].representative_point()
    cx, cy = proj(c.x, c.y)
    areas.append(
        f'<a href="<%= mapLink({json.dumps(region)}) %>" class="cov-area cov-{group}" '
        f'style="--i:{i}" data-name="{label}" data-cx="{cx:.0f}" data-cy="{cy:.0f}" aria-label="{label}">'
        f'<path d="{d}"/></a>'
    )

def centroid_of(names):
    c = unary_union([geoms[n] for n in names]).centroid
    return proj(c.x, c.y)
lx, ly = centroid_of(LONDON)
ex, ey = centroid_of(list(ESSEX))

svg = f'''<%# Generated by scripts/build-coverage-map.py — do not edit by hand. %>
<svg class="cov-map" viewBox="0 0 {W:.0f} {H:.0f}" xmlns="http://www.w3.org/2000/svg" aria-labelledby="cov-map-title">
  <title id="cov-map-title">Map of the London boroughs and Essex towns SN Cleaning Services covers</title>
  <g class="cov-context" aria-hidden="true">{''.join(context)}</g>
  <g class="cov-areas">{''.join(areas)}</g>
  <g class="cov-labels" aria-hidden="true">
    <text x="{lx:.0f}" y="{ly:.0f}">London</text>
    <text x="{ex:.0f}" y="{ey:.0f}">Essex</text>
  </g>
</svg>
'''
open(OUT, 'w').write(svg)
print('wrote', OUT, len(svg), 'bytes', f'viewBox 1000x{H:.0f}', len(context), 'context', len(areas), 'areas')
